### ISSUE TITLE
Question. How do I add a multipart section for file content that's already in memory?

### ISSUE THREAD

**Issue by restlessronin** [breakroom/multipart#14]
I've created an [OpenAI API client for elixir](https://github.com/restlessronin/openai_ex). Currently I'm using Tesla because it already supports multi-part file uploads. I'd like to switch to using Finch with `multipart`.

I'm looking for the equivalent of `Tesla.Multipart.add_file_content`, but there doesn't seem to be one. 

I'd be happy to create a PR that would provide it if you're interested.

UPDATE. I have created PR #15 which I am already using in my library.

**Comment by tomtaylor** [comment]
Released in 0.4.0.
